"""empty message

Revision ID: fa8018d83a0b
Revises: 91c1eaca1aa1
Create Date: 2021-03-22 13:26:50.711789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8018d83a0b'
down_revision = '91c1eaca1aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('numBath', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'numBath')
    # ### end Alembic commands ###
